### PR TITLE
Refactor stream transformer

### PR DESCRIPTION
**Pull request by hoc081098**
* Rewriting forward stream transformer, now doesn't need `SafeClose` interface to fix close behavior
* Cancel subscriptions of other streams when source stream is cancelled
* Fix some typos in `CompositeSubscription`
* Using `Stream.value(value)` instead of `Stream.fromIterables([value])` in `OnErrorExtensions`
* `_TakeWhileInclusiveStreamSink` implements `EventSink` instead of `ForwardingSink`

### CODE REVIEW

**Comment by frankpepermans** [comment]
That's a big one :)

I guess the biggest change would be, instead of using Stream.eventTransformed and providing a Sink, you're opted to calling that same sink, but directly from the controller, and returning its Stream?

Stream.eventTransformed kind of does this behind the scenes, right now, I guess my only concern would be that if they decide to optimise the inner workings behind the scenes, we'd lose out on that.

Other than that, it does simplify things.

Thanks!

**Comment by frankpepermans** [comment]
I've been able to try out this PR in a large project now, looks good so far.
Gonna do this for a few days, if nothing pops up, then ok to merge for me.

**Comment by frankpepermans** [comment]
Couldn't spot any issues after almost a week of running it in a very large app,
merged!

**Comment by hoc081098** [comment]
Oh, I'm glad for that 👍

**Pull request merged**
