### PR TITLE
Updated rxdart sample code.

### PR DESCRIPTION
**Pull request by sureshg**
Update sample code to use the idiomatic dart stream API to get keyup events.

### CODE REVIEW

**Comment by dotdotcommadot** [comment]
Looks like this solves the same issue as https://github.com/ReactiveX/rxdart/pull/54 does

**Comment by dotdotcommadot** [comment]
Hey @sureshg ,
Thanks a lot for your contribution, but since we have fixed the same issue, is it ok if I take your keycodes (which are better then mine) and we merge from my PR?

Might want to check the other PR's next time and join us on https://gitter.im/ReactiveX/rxdart :)
Hans

**Comment by sureshg** [comment]
@dotdotcommadot sure..which ever works for you 😄

**Comment by brianegan** [comment]
@sureshg Hey, thanks again for the contribution! We've gone ahead and taken the best parts of this refactor into the other branch :)

Gonna close this one out for now!

**Pull request closed without merging**
