### PR TITLE
fix refCount, update ConnectableStream

### LINKED ISSUE #514: Transforming a broadcast stream with share() doesn't respect refCount
The following test times out:

```dart
test('can cancel shared stream when no listeners remain', () async {
  final isDone = Completer();

  final controller = StreamController.broadcast();
  final stream = controller.stream.share().doOnDone(isDone.complete);
  StreamSubscription subscription;
  subscription = stream.listen((event) async {
    await subscription.cancel();
  });
  expect(isDone.future, completes);
});
```

The `stream`'s underlying PublishSubject always shows that it has a listener, even before the listen method is called.

The refCount doesn't appear to be respected (and the stream, therefore, isn't shut down when no listeners remain)  when transforming broadcast streams.

### PR DESCRIPTION
**Pull request by hoc081098**
Fixes #514 
Related: dart-lang/sdk#26686,  #455
- Cancel source subscription when shared stream, zip, merge, concat stream cancel
- Forward done event, #288

### CODE REVIEW

**Comment by smkhalsa** [comment]
@hoc081098 Thanks so much. These changes resolve the issues for me.

**Comment by smkhalsa** [comment]
@frankpepermans @hoc081098  can we get this merged and published please?

**Comment by smkhalsa** [comment]
@hoc081098 Is there anything I can do to help get this merged and published?

This is a blocker for gql-dart/ferry#96.

**Review by frankpepermans — APPROVED** [review]

**Comment by hoc081098** [comment]
Merged

**Comment by smkhalsa** [comment]
Awesome! Thanks so much, guys.

Can we get a new `beta` release published?

**Comment by hoc081098** [comment]
@smkhalsa https://pub.dev/packages/rxdart/versions/0.25.0-beta3 is released

**Comment by smkhalsa** [comment]
Awesome, thank you!

**Pull request merged**
