### PR TITLE
refactor(min, max): rewrite min, max operator without sorting

### PR DESCRIPTION
**Pull request by hoc081098**
Rewrite min, max operator without sorting list

### CODE REVIEW

**Comment by frankpepermans** [comment]
I was thinking we could optimise it better though, if a large amount of say, 1 million events is being added, then we still have a performance hit onDone, with the old sort or the reduce loop.

Maybe we can just subscribe instead, and on every added event run the compare, and keep the current min/max, which repeats on the next emitted event?

**Comment by hoc081098** [comment]
I removed `toList`, replaced by listening stream and repeatedly applying `comparator`

**Comment by frankpepermans** [comment]
Looks good!

**Comment by brianegan** [comment]
Woohoo! Great rewrite :)

**Pull request merged**
