### PR TITLE
Add addTo extension method for StreamSubscription

### PR DESCRIPTION
**Pull request by jarekb123**
addTo extension method - adds subscription to CompositeSubscription

Example
```dart
final subscriptions = CompositeSubscription();

stream
   .listen((data) => print(data))
   .addTo(subscriptions)
```

### CODE REVIEW

**Comment by Wheater** [comment]
Wow, that looks very nice!

**Comment by frankpepermans** [comment]
I like the idea, just thinking out loud, for discoverability, how about

```
final subscriptions = CompositeSubscription();

stream
   .listenManaged((data) => print(data), compositeSubscription: subscriptions);
```

**Comment by frankpepermans** [comment]
...or
compositeSubscription.listen(stream, onData: ...)

**Comment by brianegan** [comment]
I like it! @frankpepermans -- sorry, I'm a bit confused about your suggestions. The `CompositeSubscription` class already has the `add` method which takes in the StreamSubscription, so I don't think it would simplify things to change that up.

I think it's kind of a nice and simple extension that fits well with Rx.

**Comment by jarekb123** [comment]
The syntax comes from RxKotlin.

https://github.com/ReactiveX/RxKotlin/blob/3.x/src/main/kotlin/io/reactivex/rxjava3/kotlin/disposable.kt

**Comment by frankpepermans** [comment]
Oh, I actually meant to change the `CompositeSubscription` to have `addStream` and `addSubscription`.

For the record, I like this PR too, was just bringing up possible alternatives.

**Pull request merged**
