### PR TITLE
makes refCount emit 'emitsDone' events (#277)

### PR DESCRIPTION
**Pull request by modulovalue**
I believe this is a bug (#277). This would fix it.

### CODE REVIEW

**Comment by modulovalue** [comment]
Could someone help me out with that?

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by frankpepermans** [comment]
Yeah, code cov fails as of Dart 2.3.0, I've opened an issue at Google to investigate.

**Comment by brianegan** [comment]
Thanks so much! Sorry, needed some time to check the other implementations and make sure they follow this same behavior -- and it seems they do! 

Overall, I think this is the right call with `refCount`. Tests are passing but coverage is failing, I say we merge it up :)

**Comment by modulovalue** [comment]
Hey, sorry for using my master branch in this pull request, lesson learned. Should I open a new one? This pull request is only meant to contain 3b95ec81d3aa4f348a28cb7d9175979d06665f21

**Pull request closed without merging**
